repos:
  - repo: local
    hooks:
      - id: checkstyle
        name: checkstyle
        entry: mvn checkstyle:check
        language: system
        types: [java]
        pass_filenames: false
        always_run: true
