# Main application configuration
spring:
  application:
    name: ${APP_NAME:backend-template}

  # Active profile configuration
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  # Jackson configuration for JSON processing
  jackson:
    default-property-inclusion: non-null
    serialization:
      write-dates-as-timestamps: false
    time-zone: ${APP_TIMEZONE:UTC}

# Server configuration
server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: ${SERVER_CONTEXT_PATH:/api}

# Management endpoints (Actuator)
management:
  endpoints:
    web:
      exposure:
        include: ${MANAGEMENT_ENDPOINTS:health,info,metrics}
  endpoint:
    health:
      show-details: ${HEALTH_SHOW_DETAILS:when-authorized}

# Logging configuration
logging:
  level:
    "[com.cs301.backend]": ${LOG_LEVEL_APP:INFO}
    "[org.springframework]": ${LOG_LEVEL_SPRING:WARN}
    "[org.hibernate]": ${LOG_LEVEL_HIBERNATE:WARN}
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# OpenAPI/Swagger configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: ${SWAGGER_ENABLED:true}

# Application-specific configuration
app:
  name: ${APP_NAME:CS301 Backend Template}
  version: ${APP_VERSION:1.0.0}
  description: ${APP_DESCRIPTION:A standardized Spring Boot backend service template}
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:8080}
    allowed-methods: ${CORS_ALLOWED_METHODS:GET,POST,PUT,DELETE,OPTIONS}
    allowed-headers: ${CORS_ALLOWED_HEADERS:*}
    allow-credentials: ${CORS_ALLOW_CREDENTIALS:true}
